import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../styles/global.scss";

const roboto = Roboto({
	subsets: ["latin", "cyrillic"],
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Test for Labs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable}`}>{children}</body>
		</html>
	);
}
