import type {Metadata} from "next";
import {Inter, Roboto_Mono} from "next/font/google";
import "../styles/global.scss";

const inter = Inter({
	subsets: ["latin", "cyrillic"],
	variable: "--font-primary",
});

const robotoMono = Roboto_Mono({
	subsets: ["latin", "cyrillic"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Test for Labs",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${robotoMono.variable}`}>{children}</body>
		</html>
	);
}
